### ISSUE TITLE
How do you relax?

### ISSUE THREAD

**Issue by assertchris** [svpernova09/ama#1]

**Comment by svpernova09** [comment]
Depending on how stressed out I am, it can vary. The most tried and true method seems to be video games. I've always found Hockey video games (once I've figured out the ins and outs of the game) to be great for zoning out and playing the game. Usually I'm not even thinking about the game, I'm just going through the motions to score points and do whatever the game needs. For some reason it's very relaxing for me. If I know I need to go to bed and I'm not really feeling it I'll go play a game and usually after I'm wound down enough for bed.

A lot of vocal trance music is pretty relaxing as well. I was never into trance/dance/edm/whatever the kids call it until the past few years. I think it occupies the excitable / wandering part of my brain enough to where I can focus.
