### ISSUE TITLE
What does your problem-solving process look like?

### ISSUE THREAD

**Issue by CarlMungazi** [svpernova09/ama#8]

**Comment by svpernova09** [comment]
Once I've verified an issue (being able to reliably reproduce the behavior) I like to add a test to make sure once it's been fixed we won't see the issue again (regression testing!) Apply a fix and then push the changes upstream after making sure it's been resolved.

The actual problem solving process is pretty basic. I try to break down all the affected moving parts to isolate where / when the unwanted behavior is happening, that way it's easier to grasp the entire issue. 

If it's a bigger issue, I may bring in help / colleagues / other developers to help. From formulating a strategy to resolve the issue to making sure we're looking at the bigger picture with the affected change.
